### ISSUE TITLE
bundler is missing from the dependencies

### ISSUE THREAD

**Issue by spidey** [danger/danger-gitlab-gem#10]
On a new container I'm using `gem install danger-gitlab` but `danger` is complaning about `bundler` missing when actually running. Running `gem install danger-gitlab bundler` instead solves it.

**Comment by manicmaniac** [comment]
I think this is not a problem of `danger-gitlab` but `danger`.
I just opened a new issue https://github.com/danger/danger/issues/1425.

So let me close this one.
