### ISSUE TITLE
Initializing Dangerfile with GitLab

### ISSUE THREAD

**Issue by sasikiran** [danger/danger-gitlab-gem#2]
Hi,
 I am trying to configure Danger with our GitLab setup at work. I've both danger and danger-gitlab gems installed. Whenever I do ``danger init``, it creates Dangerfile with GitHub defaults and shows tips on creating a GitHub account for the bot etc. How do I get this configured with GitLab? I am not sure if I am missing anything. I tried ``danger-gitlab init`` which is not a valid command.

Thanks.

**Comment by JuanitoFatas** [comment]
This gem is a dependency of danger, please create an issue on github.com/danger/danger instead, thank you!
