### ISSUE TITLE
Danger locked to version 6.x prevent update to 8

### ISSUE THREAD

**Issue by fabio-gallonetto** [danger/danger-gitlab-gem#8]
Is the version locking really necessary for `danger`?

**Comment by orta** [comment]
Nah, probably not, I think this could turn to a "*"

**Comment by fabio-gallonetto** [comment]
The only reason I see to keep a version pinned is to be able to sync danger version with danger-gitlab version, at least on majors. This requires an update to the danger-gitlab gem every time a new (major) version of danger comes out - not sure if it's feasible.
Otherwise #9 removes the pinning
